---
- include: debian/git.yml
  when: ansible_os_family == 'Debian'

- include: osx/git.yml
  when: ansible_os_family == 'Darwin'

- include: debian/gitsh.yml
  when: install_gitsh and ansible_os_family == 'Debian'

- include: osx/gitsh.yml
  when: install_gitsh and ansible_os_family == 'Darwin'

- include: debian/hub.yml
  when: install_hub and ansible_os_family == 'Debian'

- include: osx/hub.yml
  when: install_hub and ansible_os_family == 'Darwin'
