---
- include: debian/git.yml
  when: ansible_os_family == 'Debian'

- include: osx/git.yml
  when: ansible_os_family == 'Darwin'

- include: hub.yml
  when: git_install_hub

- include: gitsh.yml
  when: git_install_gitsh
