- name: Download gitsh
  get_url:
    url: https://github.com/thoughtbot/gitsh/releases/download/v{{ git_version_gitsh }}/gitsh-{{ git_version_gitsh }}.tar.gz
    dest: /tmp/gitsh-{{ git_version_gitsh }}.tar.gz

- name: Extract gitsh
  unarchive: src=/tmp/gitsh-{{ git_version_gitsh }}.tar.gz dest=/tmp/gitsh-{{ git_version_gitsh }}

- name: Install gitsh
  shell: chdir=/tmp/gitsh-{{ git_version_gitsh }} {{ item }}
  with_items:
    - ./configure
    - make
    - sudo make install
