- name: Download hub
  get_url:
    creates: "{{ git_utility_root }}/hub"
    url: https://github.com/github/hub/releases/download/v{{ git_version_hub }}/hub-linux-amd64-{{ git_version_hub }}.tar.gz
    dest: /tmp/hub-linux-amd64-{{ git_version_hub }}.tar.gz

- name: Extract hub
  unarchive:
    creates: "{{ git_utility_root }}/hub"
    src: /tmp/hub-linux-amd64-{{ git_version_hub }}.tar.gz dest=/tmp

- name: Install hub
  command: mv /tmp/hub-linux-amd64-{{ git_version_hub }}/hub {{ git_utility_root }}/hub
